- index.js
#My first change to index.js
- added a greeting
- created a sum function 
- called the function
> create sum function

- index.js
> this commit is mariana

- package-lock.json
- package.json
- src/App.js
> Pt00 router

- src/assets/styles/pages/errorPage.scss
I'm sorry Leonel but in the last PR I forgot the .scss with the styles of ErrorPage
> add errorPage.scss

- src/App.js
- src/App.test.js
- src/actions/constants.js
- src/actions/getUserData.js
- src/actions/login.js
- src/actions/logout.js
- src/actions/register.js
- src/assets/styles/components/PrivateRoute.scss
- src/assets/styles/pages/register.scss
- src/components/FormTutor.js
- src/components/Header.js
- src/index.js
- src/pages/HomePage.js
- src/pages/LandingPage.js
- src/pages/LoginPage.js
- src/pages/Register.js
- src/reducers/index.js
- src/store.js
- src/test/App.test.js
- src/test/login.test.js
- src/utils/PrivateRoute.js
- src/utils/history.js
##Private Route Implementation
- created a constants file and organized imports
- implemented private routes
> Pt00 private routes

- src/App.js
This pull request is made to resolve the issue posted by Germán.
- Changed the way to get the token from redux in App.js to avoid rerenders
> Resolve app.js performance issue with redux

- src/App.js
- src/reducers/index.js
> Fix private route logic

- src/assets/styles/pages/register.scss
- src/components/FormTutor.js
- src/pages/Register.js
> Add categories from backend to the register page

- src/assets/styles/components/tutorCards.scss
- src/components/CardContainer.js
- src/components/CategoriesBar.js
- src/components/TutorsContainer.js
- src/components/tutorsCard.js
Get information from backend to TutorsContainer component
> get information from backend to TutorsContainer component

- src/App.js
- src/utils/ScrollToTop.js
Added a new component that scrolls the current page to top on every route change
> Add ScrollToTop component

- src/components/Header.js
Add onBlur event listener to close the collapsible menu when the user clicks outside the image
> Correction to header component

- src/components/CardContainer.js
- src/components/CategoriesBar.js
- src/components/tutorsCard.js
- src/test/tutorsContainner.test.js
Add TutorsContainer test and solve keys problems in its components
> add tutorscontainer test an solve keys problem in its components

- src/assets/styles/components/tutorCards.scss
Change font-weight in tutorsCar for a better visualization
> change font-weight in card component

- src/pages/Register.js
- src/test/Register.test.js
The following unit tests were made with React Testing Library:
- Categories loading from the database
- Student Registration
- Tutor registration
> Create register page test

- src/components/Review.js
- src/components/TutorPageHead.js
- src/pages/TutorDetailsPage.js
- src/test/App.test.js
- src/test/TutorsDetailsPage.test.js
- src/test/login.test.js
Tested the following:
- loading of data from mock data base
- correct renderization of loaded elements
- button redirection functionality
> Tutor details page testing and other fixes

- src/test/App.test.js
delete register test from app test
> Delete register test

- src/App.js
- src/assets/styles/pages/TutorEditProfile.scss
- src/pages/TutorProfilePage.js
- src/utils/ProfileRouteComponent.js
- Move edit button to top for better user experience
- Remove resizable feature from of the description field
- Add tutor page to profile route component
> add tutor page to profile route component, fix description field

- src/actions/getUserData.js
- src/pages/TutorProfilePage.js
- src/reducers/index.js
add the necessary data for tutor profile update
> Fix functionality with backend

- src/pages/searchPage.js
> solve warnings in search page

- src/App.js
- src/assets/styles/components/tutorProfileTutorships.scss
- src/components/tutorCancelTutorship.js
- src/components/tutorProfileTutorships.js
- src/pages/TutorshipHistory.js
- src/pages/TutorshipPage.js
Add tutorships history to the tutors profile
> add tutorship history to tutors profile

- src/assets/styles/components/tutorCards.scss
- src/components/tutorsCard.js
> add price to tutors cards
